### ISSUE TITLE
AKKA error

### ISSUE THREAD

**Issue by Nuwan-Walisundara** [i13-msrg/vibes#6]
it gives a following error for a web request:
23:45:10.087 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - HANDLE ERRORS... akka.http.scaladsl.server.Directive$$anon$1@6945c534 <function1> <function1>
23:45:10.087 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - GET...
23:45:10.087 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - WITHREQUESTTIMEOUT...
23:45:10.087 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - PARAMETERS...
23:45:10.091 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - ATTEMPT START... true
23:45:10.092 [VSystem-akka.actor.default-dispatcher-6] DEBUG vibes.Main$ - COMPLETE HTTP FAILURE...

-------------------------------
request:

"http://localhost:8082/vibe?strategy=BITCOIN_LIKE_BLOCKCHAIN&simulateUntil=1566929626201&blockTime=600&numberOfNeighbours=4&numberOfNodes=20&neighboursDiscoveryInterval=3000&latency=900&transactionSize=1000&maxBlockSize=50&throughput=50&transactionWeight=2000&maxBlockWeight=200000&networkBandwidth=1&transactionPropagationDelay=150&hashRate=40&confirmations=2&transactionFee=0"

**Comment by FabianSchuessler** [comment]
Your other issue (https://github.com/i13-msrg/vibes/issues/5) seems to indicate that your backend is not running yet. A running backend is necessary for this URL to resolve.

If you provide me with more detailed information about what you did and/ or a screenshot of your complete setup, then I might be able to help you.

**Comment by Nuwan-Walisundara** [comment]
As in the description Attacks-simulation-thesis.pdf page 82 steps as follows:

1.to install sbt i followed :
	https://www.scala-sbt.org/download.html-->Linux (deb)
2.git clone git@github.com:i13-msrg/vibes.git & cd vibes
3.cd frontend/
4.yarn install
5.cd ..
6.sbt server/run


enviroment
	NAME="Ubuntu"
	VERSION="18.04.3 LTS (Bionic Beaver)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 18.04.3 LTS"
	VERSION_ID="18.04"
	HOME_URL="https://www.ubuntu.com/"
	SUPPORT_URL="https://help.ubuntu.com/"
	BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
	PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
	VERSION_CODENAME=bionic
	UBUNTU_CODENAME=bionic


![ErrorOnRequest](https://user-images.githubusercontent.com/12545131/63984568-84759580-cae9-11e9-9528-593dec4b2995.png)
![SErverStart-](https://user-images.githubusercontent.com/12545131/63984580-935c4800-cae9-11e9-86bb-50c2ceabbdb7.png)
![vibesScreenshot from 2019-08-29 06-24-06](https://user-images.githubusercontent.com/12545131/63984592-9e16dd00-cae9-11e9-87a9-56f3697767a6.png)

**Comment by Nuwan-Walisundara** [comment]
Server startup error when run with sudo 
![Servers2019-08-30 05-59-59](https://user-images.githubusercontent.com/12545131/63985055-7de81d80-caeb-11e9-8830-2c71c2ec9195.png)

**Comment by Nuwan-Walisundara** [comment]
Seems some workaround for me:
setting the 

- TERM=xterm-color env var 

-  sbt server/compile
-sbt server/run
